# Site settings
name:曲延从的博客 
email:quyancong@126.com 
author: Yancong Qu
url: http://quyancong.github.com
resume_site:个人博客 
github: https://github.com/quyancong/
baseurl: ""
description:点滴积累
meta_description: 曲延从- 互联网开发,PHP技术栈;活到老，学到老
motto: It's our wits that make us men.
banner: 点滴积累，就是进步

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: quyancong
highlighter: Pygments

# Build settings
markdown: kramdown


FB:
  comments :
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
